### PR TITLE
fix support for CUDA 9

### PR DESCRIPTION
**Pull request by svensht2**
//cc @nbcong

### CODE REVIEW

**Comment by svensht2** [comment]
This change was done in thurst master, adopted it from there

**Comment by svensht2** [comment]
I tested it, ok to merge?

**Comment by zelonght** [comment]
@svensht2 what is personify-1.8.3 ? it's a tag/branch for a next release?

**Comment by svensht2** [comment]
its a branch

**Comment by svensht2** [comment]
its our modified version on top of thrust 1.8.3

**Comment by zelonght** [comment]
re:"modified version on top of thrust 1.8.3" - ok Simon

**Pull request merged**
